# Generated by Django 5.0.6 on 2024-06-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_description', models.TextField(blank=True)),
                ('repo_url', models.URLField()),
                ('is_private', models.BooleanField()),
            ],
        ),
    ]
