# Generated by Django 5.0.6 on 2024-06-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repo_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
